'ABNT': 'Associação Brasileira de Normas Técnicas'
'ABIH-PB': 'Associação Brasileira de Indústria de Hotéis da Paraíba'
'ABNT': 'Associação Brasileira de Normas Técnicas'
'CENSO': 'Conjunto de dados estatísticos'
'JPAC\&VB': 'João Pessoa Convention \& Visitors Bureau'
'OMT': 'Organização Mundial do Turismo'
'PBTUR': 'Empresa Paraibana de Turismo'
'SENAC': 'Serviço Nacional de Aprendizagem Comercial'
